version: "3"
services:
  web-auditor:
    #image: elasticms/web-auditor:latest
    env_file: '.env'
    ports:
      - "8686:8686"
    volumes:
      - ./docker:/app/storage
    build:
      context: ./
      dockerfile: Dockerfile
